"""empty message

Revision ID: 9abc0f565a66
Revises: dda0915a654a
Create Date: 2018-10-27 07:05:46.870801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abc0f565a66'
down_revision = 'dda0915a654a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('container_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'container_id')
    # ### end Alembic commands ###
