"""empty message

Revision ID: ce6cd3804c7b
Revises: c4ef6740cd37
Create Date: 2018-10-26 14:45:21.351963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6cd3804c7b'
down_revision = 'c4ef6740cd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('collateral_key', sa.String(length=250), nullable=True))
    op.add_column('nodes', sa.Column('mnkey', sa.String(length=250), nullable=True))
    op.drop_column('nodes', 'output_txhash')
    op.drop_column('nodes', 'output_txid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('output_txid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('nodes', sa.Column('output_txhash', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('nodes', 'mnkey')
    op.drop_column('nodes', 'collateral_key')
    # ### end Alembic commands ###
