"""empty message

Revision ID: dda0915a654a
Revises: edc69de1f5f9
Create Date: 2018-10-27 06:54:51.674667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda0915a654a'
down_revision = 'edc69de1f5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('container_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'container_name')
    # ### end Alembic commands ###
