"""empty message

Revision ID: edc69de1f5f9
Revises: ce6cd3804c7b
Create Date: 2018-10-26 16:03:44.843232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc69de1f5f9'
down_revision = 'ce6cd3804c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('output_txhash', sa.String(length=250), nullable=False))
    op.add_column('nodes', sa.Column('output_txid', sa.Integer(), nullable=False))
    op.alter_column('nodes', 'mnkey',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'mnkey',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_column('nodes', 'output_txid')
    op.drop_column('nodes', 'output_txhash')
    # ### end Alembic commands ###
